# ---- KEYBINDS ---- #
set-option -g default-terminal "screen-256color"

# set leader key to Ctrl-k
set -g prefix C-k
unbind C-b
bind-key C-k send-prefix

# set | key to horizontal split
unbind %
bind | split-window -h

# set - key to vertical split
unbind '"'
bind - split-window -v

# visual/yank keyboard for tmux vi copy mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel

# pane navigation
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# ---- SETTINGS ---- #
setw -g mode-keys vi

# set status bar location
set -g status-position bottom
set -g status-interval 1

# mouse support
set -g mouse on

# start window indexing at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# nvim intergration
set-option -g focus-events on
# Zero escape delay
set-option -s escape-time 0

set-option -g allow-rename off
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_bar_bg_disable_color_option '0'
set -g monitor-activity on
